Park.create(name: 'Acadia', location: 'Maine', latitude: '44.35', longitude: '-68.21', established: 'February 26, 1919', main_image: 'acadia.jpg')
Park.create(name: 'American Samoa', location: 'American Samoa', latitude: '-14.25', longitude: '-170.68', established: 'October 31, 1988', main_image: 'american-samoa.jpg')
Park.create(name: 'Arches', location: 'Utah', latitude: '38.68', longitude: '-109.57', established: 'April 12, 1929', main_image: 'arches.jpg')
Park.create(name: 'Badlands', location: 'South Dakota', latitude: '43.75', longitude: '-102.50', established: 'November 10, 1978', main_image: 'badlands.jpg')
Park.create(name: 'Big Bend', location: 'Texas', latitude: '29.25', longitude: '-103.25', established: 'June 12, 1944', main_image: 'big-bend.jpg')
Park.create(name: 'Biscayne', location: 'Florida', latitude: '25.65', longitude: '-80.08', established: 'June 28, 1980', main_image: 'biscayne.jpg')
Park.create(name: 'Black Canyon of the Gunnison', location: 'Colorado', latitude: '38.57', longitude: '-107.72', established: 'October 21, 1999', main_image: 'black-canyon-of-the-gunnison.jpg')
Park.create(name: 'Bryce Canyon', location: 'Utah', latitude: '37.57', longitude: '-112.18', established: 'February 25, 1928', main_image: 'bryce-canyon.jpg')
Park.create(name: 'Canyonlands', location: 'Utah', latitude: '38.20', longitude: '-109.93', established: 'September 12, 1964', main_image: 'canyonlands.jpg')
Park.create(name: 'Capitol Reef', location: 'Utah', latitude: '38.20', longitude: '-111.17', established: 'December 18, 1971', main_image: 'capitol-reef.jpg')
Park.create(name: 'Carlsbad Caverns', location: 'New Mexico', latitude: '32.17', longitude: '-104.44', established: 'May 14, 1930', main_image: 'carlsbad.jpg')
Park.create(name: 'Channel Islands', location: 'California', latitude: '34.01', longitude: '-119.42', established: 'March 5, 1980', main_image: 'channel-islands.jpg')
Park.create(name: 'Congaree', location: 'South Carolina', latitude: '33.78', longitude: '-80.78', established: 'November 10, 2003', main_image: 'congaree.jpg')
Park.create(name: 'Crater Lake', location: 'Oregon', latitude: '42.94', longitude: '-122.10', established: 'May 22, 1902', main_image: 'crater-lake.jpg')
Park.create(name: 'Cuyahoga Valley', location: 'Ohio', latitude: '41.24', longitude: '-81.55', established: 'October 11, 2000', main_image: 'cuyahoga-valley.jpg')
Park.create(name: 'Death Valley', location: 'California, Nevada', latitude: '36.24', longitude: '-116.82', established: 'October 31, 1994', main_image: 'death-valley.jpg')
Park.create(name: 'Denali', location: 'Alaska', latitude: '63.33', longitude: '-150.50', established: 'February 26, 1917', main_image: 'denali.jpg')
Park.create(name: 'Dry Tortugas', location: 'Florida', latitude: '24.63', longitude: '-82.87', established: 'October 26, 1992', main_image: 'dry-tortugas.jpg')
Park.create(name: 'Everglades', location: 'Florida', latitude: '25.32', longitude: '-80.93', established: 'May 30, 1934', main_image: 'everglades.jpg')
Park.create(name: 'Gates of the Arctic', location: 'Alaska', latitude: '67.78', longitude: '-153.30', established: 'December 2, 1980', main_image: 'gates-of-the-arctic.jpg')
Park.create(name: 'Glacier', location: 'Montana', latitude: '48.80', longitude: '-114.00', established: 'May 11, 1910', main_image: 'glacier.jpg')
Park.create(name: 'Glacier Bay', location: 'Alaska', latitude: '58.50', longitude: '-137.00', established: 'December 2, 1980', main_image: 'glacier-bay.jpg')
Park.create(name: 'Grand Canyon', location: 'Arizona', latitude: '36.06', longitude: '-112.14', established: 'February 26, 1919', main_image: 'grand-canyon.jpg')
Park.create(name: 'Grand Teton', location: 'Wyoming', latitude: '43.73', longitude: '-110.80', established: 'February 26, 1929', main_image: 'grand-teton.jpg')
Park.create(name: 'Great Basin', location: 'Nevada', latitude: '38.98', longitude: '-114.30', established: 'October 27, 1986', main_image: 'great-basin.jpg')
Park.create(name: 'Great Sand Dunes', location: 'Colorado', latitude: '37.73', longitude: '-105.51', established: 'September 13, 2004', main_image: 'great-sand-dunes.jpg')
Park.create(name: 'Great Smoky Mountains', location: 'North Carolina, Tennessee', latitude: '35.68', longitude: '-83.53', established: 'June 15, 1934', main_image: 'great-smoky-mountains.jpg')
Park.create(name: 'Guadalupe Mountains', location: 'Texas', latitude: '31.92', longitude: '-104.87', established: 'October 15, 1966', main_image: 'guadalupe-mountains.jpg')
Park.create(name: 'Haleakalā', location: 'Hawaii', latitude: '20.72', longitude: '-156.17', established: 'August 1, 1916', main_image: 'haleakala.jpg')
Park.create(name: 'Hawaii Volcanoes', location: 'Hawaii', latitude: '19.38', longitude: '-155.20', established: 'August 1, 1916', main_image: 'hawaii-volcanoes.jpg')
Park.create(name: 'Hot Springs', location: 'Arkansas', latitude: '34.51', longitude: '-93.05', established: 'March 4, 1921', main_image: 'hot-springs.jpg')
Park.create(name: 'Isle Royale', location: 'Michigan', latitude: '48.10', longitude: '-88.55', established: 'April 3, 1940', main_image: 'isle-royale.jpg')
Park.create(name: 'Joshua Tree', location: 'California', latitude: '33.79', longitude: '-115.90', established: 'October 31, 1994', main_image: 'joshua-tree.jpg')
Park.create(name: 'Katmai', location: 'Alaska', latitude: '58.50', longitude: '-155.00', established: 'December 2, 1980', main_image: 'katmai.jpg')
Park.create(name: 'Kenai Fjords', location: 'Alaska', latitude: '59.92', longitude: '-149.65', established: 'December 2, 1980', main_image: 'kenai-fjords.jpg')
Park.create(name: 'Kings Canyon', location: 'California', latitude: '36.80', longitude: '-118.55', established: 'March 4, 1940', main_image: 'kings-canyon.jpg')
Park.create(name: 'Kobuk Valley', location: 'Alaska', latitude: '67.55', longitude: '-159.28', established: 'December 2, 1980', main_image: 'kobuk-valley.jpg')
Park.create(name: 'Lake Clark', location: 'Alaska', latitude: '60.97', longitude: '-153.42', established: 'December 2, 1980', main_image: 'lake-clark.jpg')
Park.create(name: 'Lassen Volcanic', location: 'California', latitude: '40.49', longitude: '-121.51', established: 'August 9, 1916', main_image: 'lassen-volcanic.jpg')
Park.create(name: 'Mammoth Cave', location: 'Kentucky', latitude: '37.18', longitude: '-86.10', established: 'July 1, 1941', main_image: 'mammoth-cave.jpg')
Park.create(name: 'Mesa Verde', location: 'Colorado', latitude: '37.18', longitude: '-108.49', established: 'June 29, 1906', main_image: 'mesa-verde.jpg')
Park.create(name: 'Mount Rainier', location: 'Washington', latitude: '46.85', longitude: '-121.75', established: 'March 2, 1899', main_image: 'mount-ranier.jpg')
Park.create(name: 'North Cascades', location: 'Washington', latitude: '48.70', longitude: '-121.20', established: 'October 2, 1968', main_image: 'north-cascades.jpg')
Park.create(name: 'Olympic', location: 'Washington', latitude: '47.97', longitude: '-123.50', established: 'June 29, 1938', main_image: 'olympic.jpg')
Park.create(name: 'Petrified Forest', location: 'Arizona', latitude: '35.07', longitude: '-109.78', established: 'December 9, 1962', main_image: 'petrified-forest.jpg')
Park.create(name: 'Pinnacles', location: 'California', latitude: '36.48', longitude: '-121.16', established: 'January 10, 2013', main_image: 'pinnacles.jpg')
Park.create(name: 'Redwood', location: 'California', latitude: '41.30', longitude: '-124.00', established: 'October 2, 1968', main_image: 'redwood.jpg')
Park.create(name: 'Rocky Mountain', location: 'Colorado', latitude: '40.40', longitude: '-105.58', established: 'January 26, 1915', main_image: 'rocky-mountain.jpg')
Park.create(name: 'Saguaro', location: 'Arizona', latitude: '32.25', longitude: '-110.50', established: 'October 14, 1994', main_image: 'saguaro.jpg')
Park.create(name: 'Sequoia', location: 'California', latitude: '36.43', longitude: '-118.68', established: 'September 25, 1890', main_image: 'sequoia.jpg')
Park.create(name: 'Shenandoah', location: 'Virginia', latitude: '38.53', longitude: '-78.35', established: 'May 22, 1926', main_image: 'shenandoah.jpg')
Park.create(name: 'Theodore Roosevelt', location: 'North Dakota', latitude: '46.97', longitude: '-103.45', established: 'November 10, 1978', main_image: 'theodore-roosevelt.jpg')
Park.create(name: 'Virgin Islands', location: 'U.S. Virgin Islands', latitude: '18.33', longitude: '-64.73', established: 'August 2, 1956', main_image: 'virgin-islands.jpg')
Park.create(name: 'Voyageurs', location: 'Minnesota', latitude: '48.50', longitude: '-92.88', established: 'January 8, 1971', main_image: 'voyageurs.jpg')
Park.create(name: 'Wind Cave', location: 'South Dakota', latitude: '43.57', longitude: '-103.48', established: 'January 9, 1903', main_image: 'wind-cave.jpg')
Park.create(name: 'Wrangell–St. Elias', location: 'Alaska', latitude: '61.00', longitude: '-142.00', established: 'December 2, 1980', main_image: 'wrangell-st-elias.jpg')
Park.create(name: 'Yellowstone', location: 'Wyoming, Montana, Idaho', latitude: '44.60', longitude: '-110.50', established: 'March 1, 1872', main_image: 'yellowstone.jpg')
Park.create(name: 'Yosemite', location: 'California', latitude: '37.83', longitude: '-119.50', established: 'October 1, 1890', main_image: 'yosemite.jpg')
Park.create(name: 'Zion', location: 'Utah', latitude: '37.30', longitude: '-113.05', established: 'November 19, 1919', main_image: 'zion.jpg')
